// <auto-generated />
using APIs.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIs.Migrations;

[DbContext(typeof(AppDbContexto))]
[Migration("20231021071337_ChangeAppDbContextOnDelete")]
partial class ChangeAppDbContextOnDelete
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("APIs.Modelos.Aluno", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("CPF")
                    .IsRequired()
                    .HasMaxLength(11)
                    .HasColumnType("nvarchar(11)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("InstituicaoDeEnsino")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("RG")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("nvarchar(8)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("Id");

                b.ToTable("Alunos");
            });

        modelBuilder.Entity("APIs.Modelos.Empresa", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("CNPJ")
                    .IsRequired()
                    .HasMaxLength(14)
                    .HasColumnType("nvarchar(14)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("Id");

                b.ToTable("Empresas");
            });

        modelBuilder.Entity("APIs.Modelos.Endereco", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("AlunoRef")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Bairro")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("CEP")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("nvarchar(8)");

                b.Property<string>("Cidade")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<int>("Numero")
                    .HasColumnType("int");

                b.Property<string>("Rua")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.HasKey("Id");

                b.HasIndex("AlunoRef")
                    .IsUnique()
                    .HasFilter("[AlunoRef] IS NOT NULL");

                b.ToTable("Enderecos");
            });

        modelBuilder.Entity("APIs.Modelos.Endereco", b =>
            {
                b.HasOne("APIs.Modelos.Aluno", "Aluno")
                    .WithOne("Endereco")
                    .HasForeignKey("APIs.Modelos.Endereco", "AlunoRef")
                    .OnDelete(DeleteBehavior.Cascade);

                b.Navigation("Aluno");
            });

        modelBuilder.Entity("APIs.Modelos.Aluno", b =>
            {
                b.Navigation("Endereco")
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
