// <auto-generated />
using APIs.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIs.Migrations;

[DbContext(typeof(AppDbContexto))]
[Migration("20231008175035_InitialMigration1")]
partial class InitialMigration1
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("APIs.Modelos.Aluno", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("CPF")
                    .HasMaxLength(11)
                    .HasColumnType("nvarchar(11)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EnderecoId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("InstituicaoDeEnsino")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RG")
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasMaxLength(12)
                    .HasColumnType("nvarchar(12)");

                b.HasKey("Id");

                b.HasIndex("EnderecoId");

                b.ToTable("Alunos");
            });

        modelBuilder.Entity("APIs.Modelos.Empresa", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("CNPJ")
                    .HasMaxLength(14)
                    .HasColumnType("nvarchar(14)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasMaxLength(12)
                    .HasColumnType("nvarchar(12)");

                b.HasKey("Id");

                b.ToTable("Empresas");
            });

        modelBuilder.Entity("APIs.Modelos.Endereco", b =>
            {
                b.Property<string>("EnderecoId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Bairro")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("CEP")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("nvarchar(8)");

                b.Property<string>("Cidade")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<int>("Numero")
                    .HasColumnType("int");

                b.Property<string>("Rua")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.HasKey("EnderecoId");

                b.ToTable("Enderecos");
            });

        modelBuilder.Entity("APIs.Modelos.Aluno", b =>
            {
                b.HasOne("APIs.Modelos.Endereco", "Endereco")
                    .WithMany()
                    .HasForeignKey("EnderecoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Endereco");
            });
#pragma warning restore 612, 618
    }
}
